### ISSUE TITLE
How to revive CTRL+SPACE  (Default Autocompletion shortcut)?

### ISSUE THREAD

**Issue by re4lfl0w** [neobundy/cwkWritingToolKit#5]
- [Code refactoring and new features: build corpus from files(collector … · neobundy/cwkWritingToolKit@d533816 · GitHub](https://github.com/neobundy/cwkWritingToolKit/commit/d53381640b71b0bc35ad54e213ac72fff2d04d19)
- 여기 보면 

```json
[
-	{ "keys": ["ctrl+alt+space"], "command": "cwk_auto_complete" },
 	{ "keys": ["ctrl+option+shift+space"], "command": "cwk_fetch_web_dic"},
 ]
```

- cwk_auto_commplete가 삭제됐는데 이걸 어떻게 다시 살릴 수 있을까요?

### Default.sublime-commands

```json
[
	{

		"caption": "CWK Look Up Web Dictionary",
		"command": "cwk_fetch_web_dic",
	},
    {

        "caption": "CWK Look Up Auto Commplete",
        "command": "cwk_auto_complete",
    }
]
```

### Default (OSX).sublime-kemap

```json
[
	{ "keys": ["super+control+option+space"], "command": "cwk_fetch_web_dic"},
    { "keys": ["control+space"], "command": "cwk_auto_complete"},
]

```

### Context.sublime-menu

```json
[
    {
        "id": "cwkwritingtoolkit",
        "caption": "cwkWritingToolKit",
        "children":
        [
          
            {
                "caption": "Look up web dictionary",
                "command": "cwk_fetch_web_dic", "args": {"force_mode": ""}
            },
            {
                "caption": "Force Language Mode",
                "children":
                [
                    {
                        "caption": "Look up Korean", "command": "cwk_fetch_web_dic", "args": {"force_mode": "Korean"}
                    },
                    {
                        "caption": "Look up English", "command": "cwk_fetch_web_dic", "args": {"force_mode": "English"}
                    },
                    {
                        "caption": "Look up Japanese", "command": "cwk_fetch_web_dic", "args": {"force_mode": "Japanese"}
                    },

                    
                ]
            },
            {
                "caption": "Look up auto complete",
                "command": "cwk_auto_complete"
            },


        ]
    }
]

```

### Dictionaries/dictionary.cwkcsv

```
뉴뉴시, 안녕하십니까? BBC 월드 뉴스입니다.
뉴뉴끝, 지금까지 BBC 월드 뉴스였습니다. 시청해주셔서 감사합니다.
```

- 이렇게 추가해줬는데 안되네요..
- 아마 예상 답변으로는 **삽질해보세요** 가 예상되지만ㅠㅠ 그래도 한 번 여쭈어 봅니다. sublime package 만드는 법을 아름아름 찾아봐야..;
- [글쟁이/번역쟁이 용 대두족장 말뭉치 도구상자 간단 기능 소개 \- YouTube](https://www.youtube.com/watch?v=Ll96gsGZTmA&index=2&list=PLCD1oT5Fmfq9enFcHzO3nDTiPEG0dEgwU)
  - 무제한 사용자 사전이 대단하네요.
  - 상상력을 어떻게 발휘하느냐?에 따라 달라지는군요. 전 Maestro로 45h 시간 아꼈는데 대두족장님은 10days니 아직 멀었네요;

**Comment by neobundy** [comment]
'삽질' 운운할 수밖에 없는 게...^^ 

저도 한참 지나면 기억이 안 납니다. 그래서 저 또한 다시 삽질 모드 돌입해서 기억을 되살려야 하는 데 서로 엄청난 시간 낭비라서 그럽니다. 

코드 리팩터링하면서 sublime text에서 기본 제공하는 자동 완성 기능을 가로채기 때문에 따로 cwk_auto_complete 메소드를 구현할 필요가 없었던 걸로 기억합니다. 

사용자 사전은...

>ㄱㄴ, [기자 - 남]
>ㄹㅅ, 자세한 소식입니다.
>ㄱㅈ,가이 들로네, 게빈 휴잇, 닉 브라이언, 던켄 크로포드, 데이비드 로인, 라지니 바이디아나단, 로라 데이비스, 리스 두셋, 리처드포레스트, 루퍼트 윙필드헤이즈, 마리코 오이, 베스 메클로, 사라 레인즈포드, 스티브 로젠버그, 알파 베탈, 앤드류 하딩, 올라 게런, 웬디 어카트, 윌 그란트, 이메진 폭스, 제레미 보웬, 제임스 레이놀즈, 조나 피셔, 조나단 헤드, 짐 뮤어, 크리스천 프레이저, 팀 올만, 폴 우드, 프랭크 가드너, 피터 보우스, 캐티야 애들러...

이런 식입니다. 굳이 다 쓸 필요 없이 자음만 땡겨도 됩니다. 쉼표가 여러개면 맨 앞이 delimiter고 나머지는 옵션입니다. 가령 **ㄱㅈ**라고 치고 <kbd>CTRL+SPACE</kbd> 누르면 기자 이름이 좍 옵션으로 뜹니다. 사전 만들었는데 반영이 안 되면 패키지 자체를 저장해서 강제 리로딩해 보세요. 

저는 잘 쓰고 있는 터라 왜 안 되는 지 사실 잘 몰라요 ㅋ

실제로 뉴스 번역 할 때 쓰는 툴입니다. 혼자 쓰는 데 문제가 없기 때문에 오랫동안 들여다 보질 않아서ㅠ.ㅠ

네이버 사전 파싱 부분이 영 조잡해서 조만간 다시 손 댈 일이 생길 건 같은 데 언제가 될지 장담은 못하겠네요. Sublime Text가 python 3 full version을 지원하지 않아 외부 모듈을 임포트 못하기 때문에 파싱은 표준 라이브러리만 사용하느라 주먹구구일 수밖에 없거든요. 외부 모듈과 소통하는 방식으로 돌릴까 구상 중이긴 한데 귀차니즘이 태산의 압박이라ㅠ.ㅠ 

참고로...

Sublime Text 플러그인은 단순히 python만 알아서 이해하기 어렵습니다. 자체적인 메커니즘이 있기 때문에 따로 공부해야 합니다. cwk_auto_complete가 왜 사라졌고 cwk_fetch_web_dic 이 어느 클래스 타고 들어가 어떤 메소드를 실행하는지 꿰고 있어야 손 볼 수 있습니다.

아쉽게도 자료가 많지 않아서... 방법은 멘땅에 헤딩 + 삽질 뿐이랍니다ㅠㅠ

별 도움이 못 돼 미안합니다.

조만간 python에 다시 애정을 쏟아 볼게요 :)

**Comment by re4lfl0w** [comment]
## 으아... 해결했습니다.

- **삽질**이 정답이네요 :D
- 동영상에 정답이 나와있었습니다.
- 확장자가 .cwktxt인 경우에만 이 plugin이 작동하네요. 확장자를 aa.cwktxt로 하시나요?
- #3 여기 이슈가 발생한 원인: 파일을 저장하지 않고 그냥 했을때 rfind 에러가 발생하네요.
- 감동의 도가니가 몰려옵니다!! 벌써부터 흥분이 되네요. 이게 프로그래머의 맛인듯 싶어요ㅎㅎ 문제 해결했을 때의 짜릿함

![image](https://cloud.githubusercontent.com/assets/6144782/10359865/4bc3de18-6dd7-11e5-97de-fafb8f69a78e.png)

**Comment by neobundy** [comment]
아... 그 말이었군요.

당연히 저장이 안 된 파일이면 코퍼스에 포함이 안 됩니다. 파일 기준으로 긁어오기 때문에... 저장 안 한 파일은 오류 처리를 해야 하는데 역시 귀차니즘에...ㅠ.ㅠ 

확장자는 설정에서 바꾸면 됩니다. 디폴트는 `'.cwktxt', '.md'` 파일입니다.

**Comment by re4lfl0w** [comment]
근데 약간 이해가 안되는 부분이 있습니다.
Corpus 라는건 말뭉치로써 내가 지정해놓은 단어들이 있어야 한다고 생각합니다.

## 기본 세팅

```json
{
	// Toggle Debug Mode
	"debug": true,

	// Use System Voice: Mac OSX only

	"read_aloud_current_word": true,

	// System Voices

	"korean_voice": "Yuna",
	"english_voice": "Samantha",
	"japanese_voice": "Kyoko",

	// Corpus file xtensions 

	"corpus_extensions": [".cwktxt", ".md"],

	// Custom dictionary file extensions: must be a comma seperated values(csv): keyword, element1, element2, element3, etc

	"custom_dictionary_extensions": [".cwkcsv",],

	// Force rebuilding corpus on every save

	"force_rebuild_corpus_on_every_save": true,

	// Maximum autocomplete suggestions

	"max_autocomplete_suggestions": 200,

	// Method to display web dictionaries: popup, quick_panel
	"web_dic_display_method": "quick_panel"
}

```

기본 corpus_extensions로 ".cwktxt", ".md"가 포함되어 있네요.

Corpus: *.cwktxt 
내가 저장해놓은 Corpus를 사용해서 적용할 파일: *.md, *.txt

그런데 지금 <kbd>Control+Space</kbd> 을 눌러보면 aa.md의 내용도 포함이 되네요. aa.md는 제가 작성하고자 하는 파일인데..이건 왜 포함이 되는걸까요? 좀 더 생각해보니 aa.md 안에 있는것도 <kbd>Control+Space</kbd>을 눌렀을때 검색이 되야하니 포함을 하신건가요? 제가 제대로 이해한지 모르겠네요. 그렇다면 대부분 저 플러그인을 쓰는 곳은 md겠군요. 당연히 .cwktxt는 Corpus 확장자이기 때문에 사용하지 않으실것 같고요.

![image](https://cloud.githubusercontent.com/assets/6144782/10360562/8a523f3a-6ddc-11e5-9c1d-87dacdcb8d50.png)

**Comment by neobundy** [comment]
지금 쓰고 있는 문서도 전체 '책'의 일부니 당연히 포함돼야 합니다. Sublime Text 자동완성 메커니즘도 마찬가지로 현재 사용 중인 파일을 포함합니다. 확장자는 원하는 대로 지정 가능하니 확장자 따라서 갈리는 건 아닙니다.

책을 써보시면 알 지만 간단하게 사람 이름만 하더라도 지금까지 쓴 부분에서 자동으로 불러오고 싶어집니다. 프로그래밍 소스 자동완성도 마찬가지고...

현재 작업 중인 폴더 이하 모든 지정 확장자 파일에서 말뭉치를 만든다고 생각하면 됩니다. 제외할 필요가 있다면 확장자를 지정하거나 루틴을 추가해 예외 처리를 해주면 되겠지만, 아직 그럴 이유는 못 찾았네요.

파이썬 프로젝트에서 사용한다면 확장자로 ** .py** 를 지정하겠죠.그런 식입니다.

커스터마이제이션이 필요하면 소스를 입맛대로 수정하면 되요^^ 고만할 필요없이:)

대부분 만든 넘은 걍 지가 필요해서 그렇게 만들기 시작한 거니 원래 의도를 꼭 의미 둘 필요는 없습니다. 

어차피 이 프로젝트도 내가 필요해서 시작한 거니까 거의 내 니즈와 입맛에 맞출 수밖에 없었겠죠^^

**Comment by re4lfl0w** [comment]
그렇군요. 감사합니다.
입맛대로 수정하면 되겠군요 :smile:
